<?php

include_once 'lsf_subscription_postgres.inc';
include_once 'aoi_subscription_bridge.inc';

/**
 * Implements hook menu
 */
function lsf_aoi_subscriptions_menu() {
    // adds ajax endpoint to set up aoi subscriptions
    $items['aoisub/ajax'] = array(
        'title' => 'AOI SUBSCRIPTION CALLBACK ENDPOINT',
        'type' => MENU_CALLBACK,
        'page callback' => '_lsf_aoi_subscription_handler',
        'access callback' => TRUE,
    );

    return $items;
}

/**
 * Implements hook_node_view
 *
 * Adds js files for aoi subscriptions. Adds nid to page javascript.
 */
function lsf_aoi_subscriptions_node_view($node, $view_mode, $langcode) {
    if ($node->type === 'aoi_notification' && $view_mode === 'full') {
        $nid = $node->field_parent_aoi[LANGUAGE_NONE][0]['target_id'];
    } elseif ($node->type === 'aoi' && $view_mode === 'full') {
        $nid = $node->nid;
    }
    if (($node->type === 'aoi' || $node->type === 'aoi_notification') && $view_mode === 'full') {
        if (!user_is_logged_in()) {
            $logged_in = FALSE;
            $subscribed = FALSE;
        } else {
            global $user;
            $logged_in = TRUE;
            $subscribed = _check_if_user_is_subscribed($user->uid, $nid);
        }

        $aoi_vars = array(
            'is_node' => TRUE,
            'aoi_subscription' => array(
                'nid' => $nid,
                'subscribed' => $subscribed,
                'logged_in' => $logged_in,
            ),
        );
        $node->content['#attached']['js'][] = array(
            'data' => $aoi_vars,
            'type' => 'setting',
        );

        $path = drupal_get_path('module', 'lsf_aoi_subscriptions') . '/aoi_subscription_button.js';
        $node->content['#attached']['js'][] = $path;
    }
}

function lsf_aoi_subscriptions_page_alter(&$page) {
    $views_page = views_get_page_view();

    if (isset($views_page->name) && ($views_page->name == 'user_aoi_listing' || $views_page->name == 'public_aoi_listing')) {
        if (!user_is_logged_in()) {
            $logged_in = FALSE;
            $subscribed = FALSE;
        } else {
            global $user;
            $logged_in = TRUE;
        }
        global $user;
        $aoi_vars = array('is_node' => FALSE, 'aoi_subscription' => array());
        for ($i=0; $i<count($views_page->result); $i++) {
            $nid = _get_nid_from_view_result($views_page->result[$i]);
            if (!$nid) {
                continue;
            }
            if ($logged_in) {
                $subscribed = _check_if_user_is_subscribed($user->uid, $nid);
            }
            $aoi_vars['aoi_subscription'][$i] = array(
                'nid' => $nid,
                'subscribed' => $subscribed,
                'logged_in' => $logged_in,
            );
        }

        drupal_add_js($aoi_vars, 'setting');
        drupal_add_js(
            drupal_get_path('module', 'lsf_aoi_subscriptions') . '/aoi_subscription_button.js',
            array('type' => 'file', 'scope' => 'footer')
        );
    }
}

function _get_nid_from_view_result($result) {
    if (isset($result->node_field_data_field_parent_aoi_nid)) {
        return $result->node_field_data_field_parent_aoi_nid;
    }
    if (isset($result->nid)) {
        return $result->nid;
    }
    return false;
}


/**
 * General purpose handler for managing subscriptions to AOI's
 */
function _lsf_aoi_subscription_handler() {
    if (!user_is_logged_in()) {
        drupal_goto('user/register');
        return;
    }

    if ($_REQUEST['type'] === 'subscription_add') {
        $result = _handle_user_subscribe($_POST['nid']);
    }

    drupal_json_output($result);
    exit();
}

function _handle_user_subscribe ($nid) {
    global $user;

    $uid = $user->uid;

    if (_lsf_aoi_subscription_check_legacy($nid) === FALSE) {
        if (_check_if_user_is_subscribed($uid, $nid) === FALSE) {
            return _create_aoi_subscription_node($uid, $nid);
        } else {
            return _unsubscribe_user_from_aoi($uid, $nid);
        }
    } else {
        return _handle_legacy_aoi_subscription($uid, $nid);
    }
}

function _check_if_user_is_subscribed ($uid, $nid) {
    $result = db_query('SELECT COUNT(*) FROM field_data_field_parent_aoi AS aoi LEFT JOIN node ON aoi.entity_id=node.nid WHERE aoi.bundle=\'aoi_subscription\' AND node.uid = :uid AND aoi.field_parent_aoi_target_id = :nid', array(':uid' => $uid, ':nid' => $nid));
    return (intval($result->fetchAssoc()['COUNT(*)']) > 0);
}

function _unsubscribe_user_from_aoi ($uid, $nid) {
    $subscription_nid = _get_subscription_nid($uid, $nid);
    node_delete($subscription_nid);
    return 'unsubscribed';
}

function _get_subscription_nid ($uid, $nid) {
    $result = db_query('SELECT aoi.entity_id FROM field_data_field_parent_aoi AS aoi LEFT JOIN node ON aoi.entity_id=node.nid WHERE aoi.bundle=\'aoi_subscription\' AND node.uid = :uid AND aoi.field_parent_aoi_target_id = :nid', array(':uid' => $uid, ':nid' => $nid));
    return $result->fetchAssoc()['entity_id'];
}

function _create_aoi_subscription_node ($uid, $nid) {
    $values = array(
        'type' => 'aoi_subscription',
        'uid' => $uid,
        'status' => 1,
        'comment' => 0,
        'promote' => 0,
    );
    $entity = entity_create('node', $values);

    // The entity is now created, but we have not yet simplified use of it.
    // Now create an entity_metadata_wrapper around the new node entity
    // to make getting and setting values easier
    $ewrapper = entity_metadata_wrapper('node', $entity);

    $parent_node = node_load($nid);

    $ewrapper->title->set('AOI subscription for ' . $parent_node->title);

    // Set the value of the entity reference field
    // Note that the entity id must be passed as an integer not a string
    $entity->field_parent_aoi[LANGUAGE_NONE][] = array(
        'target_id' => intval($nid),
        'target_type' => 'node',
    );

    // Now just save the wrapper and the entity
    // There is some suggestion that the 'true' argument is necessary to
    // the entity save method to circumvent a bug in Entity API. If there is
    // such a bug, it almost certainly will get fixed, so make sure to check.
    $ewrapper->save();

    return 'success';
}
